# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Banco.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import sqlite3
import datetime

con = sqlite3.connect('Banco.db')
cur = con.cursor()

# Create or Connect to DataBase
try:
    cur.execute('''CREATE TABLE Banco(Data TEXT ,Motivo TEXT ,Valor Float ,Total Float)''')
    con.commit()
    print('[+] Data Base Created')
except:
    print('[+] Conection to Data Base Done')


class AddVal(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(271, 223)
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(10, 40, 251, 41))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.textEdit_2 = QtWidgets.QTextEdit(Form)
        self.textEdit_2.setGeometry(QtCore.QRect(10, 120, 251, 41))
        self.textEdit_2.setObjectName("textEdit_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(120, 170, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.pushButton.clicked.connect(self.AddValue)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.textEdit.setPlaceholderText(_translate("Form", "Motivo Gasto"))
        self.label.setText(_translate("Form", "Motivo"))
        self.label_2.setText(_translate("Form", "Valor"))
        self.textEdit_2.setPlaceholderText(_translate("Form", "Valor / - Valor"))
        self.pushButton.setText(_translate("Form", "Add"))

    def AddValue(self):
        Motivo = self.textEdit.toPlainText()
        Valor = self.textEdit_2.toPlainText()
        
        try:
            Valor = float(Valor)
        except:
            self.textEdit_2.setText('<span style=\"color:#ff0000;\"> Valor Int ou Float</span>')

        global Total
        Total = Total + float(Valor)
        cur.execute('''INSERT INTO Banco VALUES(?,?,?,?)''', [str(datetime.date.today()), Motivo, float(Valor), float(Total)])
        con.commit()
        ui.Update()



class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(647, 487)
        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setGeometry(QtCore.QRect(80, 30, 131, 381))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setBold(True)
        font.setWeight(75)
        self.listWidget.setFont(font)
        self.listWidget.setObjectName("listWidget")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(50, 430, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(210, 430, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(400, 440, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(130, 10, 67, 17))
        self.label_2.setObjectName("label_2")
        self.listWidget_2 = QtWidgets.QListWidget(Form)
        self.listWidget_2.setGeometry(QtCore.QRect(230, 30, 251, 381))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setBold(True)
        font.setWeight(75)
        self.listWidget_2.setFont(font)
        self.listWidget_2.setObjectName("listWidget_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(330, 10, 67, 17))
        self.label_3.setObjectName("label_3")
        self.listWidget_3 = QtWidgets.QListWidget(Form)
        self.listWidget_3.setGeometry(QtCore.QRect(500, 30, 131, 381))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setBold(True)
        font.setWeight(75)
        self.listWidget_3.setFont(font)
        self.listWidget_3.setObjectName("listWidget_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(540, 10, 67, 17))
        self.label_4.setObjectName("label_4")
        self.listWidget_4 = QtWidgets.QListWidget(Form)
        self.listWidget_4.setGeometry(QtCore.QRect(10, 30, 51, 381))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setBold(True)
        font.setWeight(75)
        self.listWidget_4.setFont(font)
        self.listWidget_4.setObjectName("listWidget_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(30, 10, 67, 17))
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.pushButton.clicked.connect(self.AddValues)
        self.pushButton_2.clicked.connect(self.DeleteRow)

        self.Update()
        self.listWidget_4.itemClicked.connect(self.SelectItem)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Add"))
        self.pushButton_2.setText(_translate("Form", "Delete"))
        self.label.setText(_translate("Form", "Total : 0.0€"))
        self.label_2.setText(_translate("Form", "Data"))
        self.label_3.setText(_translate("Form", "Motivo"))
        self.label_4.setText(_translate("Form", "Valor"))
        self.label_5.setText(_translate("Form", "ID"))

    def AddValues(self):
        Form1.show()

    def GetTotal(self):
        Sum = 0
        Value = cur.execute('''SELECT Valor FROM Banco''')
        for Num in Value:
            Sum += Num[0]
        global Total
        Total = float(Sum)

    def Update(self):
        self.listWidget.clear()
        self.listWidget_2.clear()
        self.listWidget_3.clear()
        self.listWidget_4.clear()
        Todos = cur.execute('''SELECT rowid ,* FROM Banco''')
        for i in Todos:
            self.listWidget_4.addItem(str(i[0]))
            self.listWidget.addItem(i[1])
            self.listWidget_2.addItem(str(i[2]))
            self.listWidget_3.addItem(str(i[3]))
        self.GetTotal()
        self.label.setText("Total : "+ str(Total)+ " €")

    def SelectItem(self, item):
        self.ID = item.text()
        
    def DeleteRow(self):
        global Total
        if self.ID != None:
            Tot = cur.execute('''SELECT MAX(rowid), Total FROM Banco''')
            for i in Tot:
                if int(self.ID) == int(i[0]):
                    cur.execute('''DELETE FROM Banco WHERE rowid = ?''', [self.ID])
                    con.commit()
                    self.Update()
                else:
                    cur.execute('''DELETE FROM Banco WHERE rowid = ?''', [self.ID])
                    con.commit()
                    self.Update()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    global Form1
    global ui
    Form1 = QtWidgets.QWidget()
    ui = Ui_Form()
    ui1 = AddVal()
    ui.setupUi(Form)
    ui1.setupUi(Form1)
    Form.show()
    sys.exit(app.exec_())
